github.com:
    users:
        bjaxqq:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: bjaxqq
